[package]
name = "gen"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "gen"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.83"
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
reqwest = { version = "0.12.8", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
rand = "0.8.5"
regex = "1.11.0"
thiserror = "1.0.64"
