timeout = 60
default_service = "hf"

[services.hf]
id = "hf"
default_model = "sd35-lg-turbo" # fastest

[[services.hf.models]]
id = "sd35-lg-turbo"
name = "stabilityai/stable-diffusion-3.5-large-turbo"
height = 1024
width = 1024
steps = 4

[[services.hf.models]]
id = "sd35-lg"
name = "stabilityai/stable-diffusion-3.5-large"
height = 1024
width = 1024
steps = 28
cfg = 3.5

[[services.hf.models]]
id = "sdxl"
name = "stabilityai/stable-diffusion-xl-base-1.0"
height = 1024
width = 1024
steps = 50
cfg = 7.5
negative_prompt = ""

[[services.hf.models]]
id = "flux-schnell"
name = "black-forest-labs/FLUX.1-schnell"
height = 1024
width = 1024
steps = 4

[[services.hf.models]]
id = "flux-dev"
name = "black-forest-labs/FLUX.1-dev"
height = 1024
width = 1024
steps = 28
cfg = 3.0

[services.together]
id = "together"
default_model = "flux-schnell"

[[services.together.models]]
id = "flux-schnell"
name = "black-forest-labs/FLUX.1-schnell-Free"
height = 1024
width = 1024
steps = 4
options = { n = 1 }

[[services.together.models]]
id = "flux11-pro"
name = "black-forest-labs/FLUX.1.1-pro"
height = 1024
width = 1024
options = { n = 1 }
